Repository AY2324S2-CS2103T-T16-3/tp, pull requests merged in 2024-03, with the labels that each got.

#21 Fix img naming to fit auto grader convention
  docs/AboutUs.md
  docs/images/gavingoh99.png
  docs/images/guanquann.png
  docs/images/maze508.png
  docs/images/sun-ruiheng.png
Labels: type.Documentation

#23 Flexible search
  README.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameAndTagContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameAndTagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#25 Add order command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/Date.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/order/DateTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#29 Add Command list orders
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListOrderCommandParser.java
  src/main/java/seedu/address/model/order/Date.java
  src/test/java/seedu/address/logic/commands/ListOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListOrderCommandParserTest.java
  src/test/java/seedu/address/model/order/DateTest.java
Labels: type.Enhancement, priority.Medium

#33 Update UG & DG for Company
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation

#34 Update DG for listorder
  docs/DeveloperGuide.md
  docs/diagrams/ListOrderSequenceDiagram.puml
  docs/diagrams/style.puml
Labels: type.Documentation

#35 Update DG for addorder
  docs/DeveloperGuide.md
  docs/diagrams/AddOrderSequenceDiagram.puml
Labels: type.Documentation

#37 Update DG for Add
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Documentation

#46 Fix UI text for listorder
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
Labels: type.Enhancement

#53 Add Model Abstraction for ListOrder
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement

#54 Change Implementation from ArrayList to List in ListOrder Command
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Enhancement

#51 Bug Fix: Commands with No Arguments
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddFavouriteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFavouriteCommand.java
  src/main/java/seedu/address/logic/commands/ShowFavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowFavouriteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/ShowFavouriteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: severity.Medium

#55 Add Delete Order Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.Medium

#39 Create Remark class for Order
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Remark.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/RemarkTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
Labels: type.Enhancement

#49 Update UI
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/heart_icon.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/ListOrderCommandTest.java
Labels: type.Task

#60 Fix date parse bug
  src/main/java/seedu/address/model/order/Date.java
Labels: type.Bug
