Repository AY2324S2-CS2103T-T16-3/tp, pull requests merged in 2024-04, with the labels that each got.

#61 Bug fixes, enhance test cases for orders
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/ListOrderCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: type.Bug

#62 Update DG for ShowFav
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ShowFavouriteSequenceDiagram.puml
Labels: type.Documentation

#68 Change to Warnings for addfav, removefav
  src/main/java/seedu/address/logic/commands/AddFavouriteCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFavouriteCommand.java
  src/test/java/seedu/address/logic/commands/AddFavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveFavouriteCommandTest.java
Labels: severity.Medium

#130 Remove duplicate order constraint
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement

#133 Update addorder sequence diagram, use case and manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddOrderSequenceDiagram.puml
Labels: type.Documentation

#132 UG and DG Enhancements and Fix Find Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Documentation

#139 Fix bugs, standarise some docs in UG and DG
  GourmetGrid User Guide.pdf
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/parser/ListFavouriteCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/ListFavouriteCommandTest.java
Labels: type.Bug, type.Documentation

#143 Update DG and UG and resolve more issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High
